config/routes.rb
Rails.application.routes.draw do
  get 'about/index'

  devise_for :users
  resources :albums do
    resources :photos
  end
  root to: 'albums#index'
end

app/models/album.rb
class Album < ApplicationRecord
  has_many :photos
  self.per_page = 6

  def self.search(search)
    where('title LIKE ?', "%#{search}%")
  end

  def title_photo
    if photos.blank?
      '/assets/default_photo.png'
    else
      photos.last.picture.url(:thumb)
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :picture, PictureUploader
  belongs_to :album
  validates_presence_of :picture
  # validates_presence_of :title
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: %i[show update edit destroy]

  def index
    @albums = Album.all
    if params[:search]
      @albums = Album.search(params[:search]).paginate(page: params[:page])
    else
      @albums = Album.paginate(page: params[:page]).order('created_at DESC')
    end
    respond_to do |format|
      format.html
      format.js { render 'album_page' }
    end
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_path(@album)
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @album.update_attributes(album_params)
      redirect_to @album
    else
      render :edit
    end
  end

  def show
  #  @album = Album.find params[:id]
  end

  def destroy
  #  @album = Album.find params[:id]
    @album.destroy
  end

  private

  def set_album
    @album ||= Album.find params[:id]
  end

  def album_params
    params.require(:album).permit(:title)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: %i[index show]
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_album
  before_action :set_photo, only: [:show, :update, :edit, :destroy]
  def index
    # @photos = Photo.all
    @photos = @album.photos.all
  end

  def new
    # @photo = Photo.new
    @photo = @album.photos.new
  end

  def create
    @photo = @album.photos.create(photo_params)
  end

  def update
    if @photo.update_attributes(photo_params)
      redirect_to @album
    else
      render :edit
    end
  end

  def destroy
    @photo.destroy
  end

  private

  def set_photo
    @photo ||= @album.photos.find params[:id]
  end

  def set_album
    @album ||= Album.find params[:album_id]
  end

  def photo_params
    params.require(:photo).permit(:title, :description, :picture)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/about/index.html.erb
<div class="row">
    <div class="col-md-1">
    </div>
    <div class="col-md-10">
      <%= image_tag("Oceans-Eleven.jpg", id: "picture",  class: "picture") %>
      <%= submit_tag "try it", id: "try-it", class: 'button-try'%>

    </div>
    <div class="col-md-1">
    </div>
</div>

app/views/albums/_album.html.erb
<div id="album_<%= album.id %>" class="album">

  <% @albums.each do |album| %>

    <%= link_to(album_path(album), class: "card", :"data-groups" => "city,") do %>
      <%= image_tag album.title_photo %>
      <div class="title"><%= album.title %></div>
    <% end %>
  <% end %>
    <% if user_signed_in? %>
    <span style="float: right"><%= link_to 'Edit', edit_album_path(album) %>
      <%= link_to '✕', album_path(album), method: :delete, remote: true, class: 'delete_post' %></span>
      <% end %>
    </div>




</div>

app/views/albums/_form.html.erb
<div class="row">
    <div class="col-md-12">

        <%= form_for( @album, html: {class: 'form-inline'}) do |f| %>
        <div class="form-group">
            <%= f.text_field :title, placeholder: "Title", class: "form-control" %>
            <%= f.submit class: "btn btn-default"%>
            <%= link_to 'Back', albums_path, class: "btn btn-default"  %>
        </div>
        <% end %>
    </div>
</div>

app/views/albums/_photo.html.erb
<div id="photo_<%= photo.id %>" class="col-sm-6 col-md-4">
    <div class="thumbnail">
        <h4>
            <%- if user_signed_in? %>
              <div class="label label-info info">
                  <span data-toggle="tooltip" title="viewed">
                      <%= link_to 'Edit', edit_album_photo_path(@album, photo) %>
                  </span>
                  <span data-toggle="tooltip" title="viewed">
                      <%= link_to '✕', album_photo_path(@album, photo), method: :delete, remote: true, class: 'delete_post' %>
                  </span>
              </div>
            <% end %>
        </h4>
        <%= link_to photo.picture_url, :class => 'swipebox' do %>
        <%= image_tag(photo.picture_url(:thumb)) %>
        <% end %>
        <p><%= photo.title %></p>
    </div>
</div>

app/views/albums/_search_results.html.erb
<%= form_tag(albums_path, :method => "get", class: 'form-inline',id: "search-form") do %>
<div class="form-group">
    <%= text_field_tag :search, params[:search], placeholder: "Search Album", class: "form-control" %>
    <%= submit_tag "Search", class: "btn btn-default"%>
</div>
<% end %>
<% unless @albums.present? %>

<div class="alert alert-danger" role="alert">

    <p>There are no album containing the term(s)
        <%= params[:search] %>.</p>
</div>
<% end %>

app/views/albums/album_page.js.erb
$('#feed').append('<%= j render @albums %>');
<% if @albums.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @albums %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

app/views/albums/create.html.erb
<h1>Create Photo </h1>

app/views/albums/destroy.js.erb
$('#album_<%= @album.id %>').remove();

app/views/albums/edit.html.erb
<h1 >Edit Album</h1>
<%= render 'form' %>

app/views/albums/index.html.erb
<center>
    <%= render 'search_results'%>
</center>

<div class="container">
    <div class="row">
        <h2 class="text-center">All Albums
        </h2>
        <hr/>
    </div>
    <div class="row">

        <% @albums.each do |album| %>

        <div id="album_<%= album.id %>" class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <h4>
                    <% if user_signed_in? %>
                    <span class="label label-info info">
                        <span data-toggle="tooltip" title="viewed"><%= link_to 'Edit', edit_album_path(album) %>
                        </span>
                        <span data-toggle="tooltip" title="viewed"><%= link_to '✕', album_path(album), method: :delete, remote: true, class: 'delete_post' %>
                        </span>
                    </span>
                    <% end %>
                </h4>
                <%= link_to(album_path(album)) do %>
                <%= image_tag album.title_photo %>
                <% end %>
                <p><%= album.title.capitalize %></p>
                <div class="clearfix"></div>
            </div>
        </div>
        <% end %>

    </div>

</div>

<center>
    <%= will_paginate @albums, renderer: BootstrapPagination::Rails %>
</center>

app/views/albums/new.html.erb
<h1>New Album</h1>
<%= render 'form' %>

app/views/albums/show.html.erb
<% if user_signed_in? %>
  <p><%= link_to 'Upload new one photo', new_album_photo_path(@album) %></p>

  <%= form_for :photos, :html => { id: 'new_photo', :multipart => true },
               url:    album_photos_path(@album, Photo.new), authenticity_token: true,
               method: :post, remote: true do |f| %>
  <div class="field">
      <%= f.label :picture, "Upload photos:" %>
      <p><%= f.file_field :picture, multiple: true, name: 'photo[picture]' , class: "btn btn-default btn-file"%></p>
  </div>
  <% end %>

  <script id="template-upload" type="text/x-tmpl">
      <div class="upload">{%=o.name%}
          <div class="progress">
              <div class="bar" style="width: 0%"></div>
          </div>
      </div>
  </script>
<% end %>

<div class="container">
    <div class="row">
        <h2 class="text-center"><%= @album.title %></h2>
        <hr/>
    </div>

    <div class="row" id="photos">
        <% @album.photos.each do |photo| %>
          <%= link_to [@album, photo] do %>
            <%= render 'photo', photo: photo %>
          <% end %>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Photo Gallery</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>

        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <a class="navbar-brand" href="/">Photo Gallery for CHPT</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active">
                            <%= link_to "Album", albums_path, :class => 'navbar-link'  %>
                        </li>
                        <% if user_signed_in? %>
                        <li>
                            <%= link_to "Add Album", new_album_path, :class => 'navbar-link'  %>
                        </li>
                        <% end %>
                        <li >
                            <%= link_to "About", about_index_path, :class => 'navbar-link'  %>
                        </li>
                    </ul>
                    <p class="navbar-text pull-right">
                        <% if user_signed_in? %>
                        Logged in as
                        <strong><%= current_user.email %></strong>.
                        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
                        |
                        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
                    <% else %>
                        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
                        |
                        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
                        <% end %>
                    </p>
                </div>
            </div>
        </nav>

        <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
        <% end %>

        <div class="container">
            <%= yield %>
        </div>
    </body>

    <footer>
        <div class="navbar navbar-default navbar-fixed-bottom">
            <div class="container">
                <p class="navbar-text pull-left">
                    Ruby on Rails #Softgroup 2017
                </p>
            </div>
        </footer>

    </html>

app/views/photos/_form.html.erb
<div class="row">
    <div class="col-md-12">

        <%= form_for [@album, @photo], remote: true, authenticity_token: true do |f| %>

        <div class="form-group">

            <%= f.label :title %>
            <br>
            <%= f.text_field :title , class: "form-control"%>
            <%= f.label :description %>
            <br>
            <%= f.text_field :description, class: "form-control" %>
            <%= f.label :picture%>
            <br>
            <%= f.file_field :picture, id: :photo_picture, class: "btn btn-default btn-file"%>
            <%= f.submit  class: "btn btn-default"%>
            or
            <%= link_to 'Cancel', album_path(@album), class: "btn btn-default" %>
        </div>

        <% end %>
    </div>
</div>

app/views/photos/_row.html.erb
<div class="photo">
  <%= link_to image_tag(photo.picture_url(:thumb)) , album_photo_path(photo)%>
  <div class="name"><%= photo.title %></div>
  <div class="actions">
    <%= link_to "edit", edit_album_photo_path(photo) %> |
    <%= link_to "remove", album_photo_path(@album, photo), :confirm => 'Are you sure?', :method => :delete %>

  </div>
</div>

app/views/photos/create.html.erb
<h1>Create Photo </h1>

app/views/photos/create.js.erb
<% if @photo.new_record? %>
  alert("Failed to upload photo: <%= j @photo.errors.full_messages.join(', ').html_safe %>");
<% else %>
  $("#photos").append("<%= j render 'albums/photo', photo: @photo %>");
  console.log("OK");
<% end %>

app/views/photos/destroy.js.erb
$('#photo_<%= @photo.id %>').remove();

app/views/photos/edit.html.erb
<h1>Edit Photo </h1>
<%= render 'form' %>
<div class="edit-img">

<%= image_tag @photo.picture_url %>
</div>

app/views/photos/new.html.erb
<h1>Creating New Photo </h1>
<%= render 'form' %>

app/views/photos/show.html.erb
<%= image_tag @photo.picture_url(:thumb) if @photo.picture.present?%> <br>
<%= @photo.title %>
<%= @photo.description %>
<p>
  <%= link_to @album.title, @album %>
  /
  <%= @photo.title %>
</p>
<%= link_to 'Edit', edit_album_photo_path(@album, @photo) %>